// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf_project/internal/modules/system/model/dao/internal"
)

// postDao is the data access object for the table system_post.
// You can define custom methods on it to extend its functionality as needed.
type postDao struct {
	*internal.PostDao
}

var (
	// Post is a globally accessible object for table system_post operations.
	Post = postDao{internal.NewPostDao()}
)

// Add your custom methods and functionality below.
